commit_message: 'i18n(%language%): crowdin update'
append_commit_message: 
files:
  - source: backend/config/locales/en.yml
    translation: backend/config/locales
  - source: frontend/i18n/en.yml
    translation: frontend/i18n/
