name: "Build all packages"

on:
  workflow_dispatch:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch build.yml for all services
        shell: bash
        run: |
          for service in backend frontend wiki sub-image sub-chart sub-audio; do
            echo "Dispatching build.yml for $service"
            curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/sevenc-nanashi/chart_cyanvas/actions/workflows/$service-check.yml/dispatches \
              -d '{"ref": "main"}' \
              -f
          done
